### ISSUE TITLE
Allow archival after stopping.

### ISSUE THREAD

**Issue by w3bb** [KararTY/ServerAutoRecordArchiverHeroine#19]
Currently DARAH will clear the cache and restart. This is super painful since Discord can sometimes time out and completely stop an operation on a huge server that would take hours to rearchive. I think it would be useful to allow DARAH to continue from cache.

**Comment by KararTY** [comment]
Implemented in the latest commit.

I've not had time to fully try it out with huge servers, I've however tried it by manually shutting down the internet connection and the backup feature seems to function.

Anyway, it needs more testing. If you find any bugs, please do report them.

**Comment by w3bb** [comment]
Will do!

**Comment by w3bb** [comment]
@KararTY Does this work with CTRL+Cing? Works exactly as it did before.

**Comment by KararTY** [comment]
CTRL+C should now work on any OS that sends "SIGINT" to the process before exit... Unfortunately, it does not seem to work with my development workshop that's running Windows, using Powershell.

I'm unable to properly have that function on Windows. If you have a solution I'd appreciate a pull-request.

However, a workaround I've found for me on Windows, is shutting down the internet adapter manually through the Control Panel. That does trigger the backup functionality.

Feel free to try it out.
